---
  lmp_binary: ""
  nprocs: "4"
  args: "-cite none"
  mpiexec: "mpirun"
  mpiexec_numproc_flag: "-np"
  tolerance:
    PotEng:
      abs: 1e-4
      rel: 1e-7
    TotEng:
      abs: 1e-4
      rel: 1e-7
    Press:
      abs: 1e-4
      rel: 1e-7
    Temp:
      abs: 1e-4
      rel: 1e-7
    E_vdwl:
      abs: 1e-3
      rel: 1e-7
  overrides:
    in.rigid.tnr:
      Temp:
        abs: 1e-3
        rel: 1e-5
      Press:
        abs: 1e-2
        rel: 1e-4
  skip:
    [ in.rigid.poems3,
      in.rigid.poems4,
      in.rigid.poems5,
      in.peptide,
      in.voronoi,
      in.voronoi.2d,
      in.voronoi.data,
      in.*_imd*,
      in.bucky-plus-cnt*,
    ]

  nugget: 1.0
  epsilon: 1e-16


